
# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ggabbiani/fedora-simage:latest

pipelines:
  branches:
    cpack.d:
      - step:
          script: # Modify the commands below to build your repository.
            - mkdir -p build/simage
            - cd build/simage
            - cmake ../.. -DCMAKE_BUILD_TYPE=MinSizeRel
            - make
            - make test
            - cpack --config cpack.d/fedora.cmake
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/build/simage/simage-devel-1.7.1a-696.fc27.x86_64.rpm,/opt/atlassian/pipelines/agent/build/build/simage/simage-libs-1.7.1a-696.fc27.x86_64.rpm"
